// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnabhukvvsluhqhmbtwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYWJodWt2dnNsdWhxaG1idHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTA1MzQsImV4cCI6MjA1Nzc2NjUzNH0.bpNOHnbt_wqIFEkT_QSPn8LZKXBoSFSMXhjS9NB4KwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);